language: ruby
sudo: required
dist: trusty

before_install:
- sudo apt-get -qq update
- sudo apt-get -y install python3-pip texlive-full
- sudo pip3 install --upgrade pip
- sudo pip3 install sphinx
- sudo pip3 install sphinx_bootstrap_theme

env:
  - COMMAND="make clean html latexpdf epub"
  
before_deploy: 
  "mv build/latex/KubuntuManual.pdf build/latex/KubuntuManual-17.10.pdf"
  
deploy:
  provider: releases
  api-key:
    secure: ru0XfAzW/WBz+FS+3+aA8f5XUk74JljJLV7m0HRTUdTOQVBDvdaTEb7oTfBCkjM/cPc/U2sb3eXITU5PAhyId+dX8ezu7swqq8I3k4v48AFg/jnUzn46GO1U4jmwAgtLfXjAqTHYrXEtjxA0Ep6EwJ4w8zmPkf4Kfr9KzJESVhMcJzv4GDykl5Gbb+vZ+aj6BxsoD1CgO59yCdrxiPrx+IScF6GBGQrhL9Xm5QqJPtEg/r3jTTIok25FoWjRIl5Un40Hza+imXlSnn8HtUq/bwwJTjYSei+b/yCk+k+q/pQd9aLTxQvkGTmWQHp8wccUyv7ee7cgnOO82IVu7uo3bgpbN1VKDt2wOa7P7UtJ5Es5NMG+IUld4M/+Cyw85I8jo9YONJHePft8WeJ3bWo+f2d3AyPItRktOBSapvPSaaUHJaN3/nAoiEEPl8ydRjV9b5JBgDA+SRRTbxFJGr0nebpCvBu1w+HsqV/B+K6F2t7FcpCAS8TJIFPi83Ot37/HzZmFgtBTN7UFN7j38d/58IaUrOEqe4QEwnKp8zWzA75W3+wm+04KtzRL7y5hY/vjxmqciI6OgqBWl4XOp6IMgo1m5Zd7xNvq4I/btUxyk0xhDUrv1HMtUItrZm03StytrdZZ+a583HNz0SszJWn2jY06ngLyYLlNXL5ng8kRSxM=
  file: 
  - "build/epub/KubuntuManual.epub"
  - "build/latex/KubuntuManual-17.10.pdf"
  skip_cleanup: true
  on:
    tags: true
    
notifications:
  email:
  - aaronhoneycutt@kubuntu.org
  irc: irc://chat.freenode.net:6667#kubuntu-devel
  slack: kubuntu:puzVpRNriVEjjGOmGqvws9FU
script:
- bash -c "$COMMAND"
